server:
  port: 8080
  
spring:
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    
  datasource:
    url: jdbc:h2:~/mystats
    username: test
    
    hikari:
      maximum-pool-size: 5

